const API_BASE_URL_DEVELOPMENT = 'http://localhost:5014';
const API_BASE_URL_PRODUCTION = '';

const ENDPOINTS = {
    GET_ALL_BOOKS:'/api/Book',
    CREATE_BOOKS:'/api/Book',
    UPDATE_BOOKS:'/api/Book/{id}',
    DELETE_BOOKS:'/api/Book/{id}',
};

const developement = {
    API_URL_GET_ALL_BOOKS:`${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_BOOKS}`,
    API_URL_CREATE_BOOKS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_BOOKS}`,
    API_URL_UPDATE_BOOKS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_BOOKS}`,
    API_URL_DELETE_BOOKS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_BOOKS}`
};

const production = {
    API_URL_GET_ALL_BOOKS:`${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_BOOKS}`,
    API_URL_CREATE_BOOKS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_BOOKS}`,
    API_URL_UPDATE_BOOKS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_BOOKS}`,
    API_URL_DELETE_BOOKS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_BOOKS}`
};

const Constants = process.env.NODE_ENV === 'development' ? developement : production;

export default Constants;
